export const CREATING_BOARD = 'CREATING_BOARD';
export const CANCEL_CREATING_BOARD = 'CANCEL_CREATING_BOARD';
export const SUBMIT_BOARD = 'SUBMIT_BOARD';
export const PUT_BOARD_INTO_COLLECTION = 'PUT_BOARD_INTO_COLLECTION';
export const SELECT_ACTIVE_BOARD = 'SELECT_ACTIVE_BOARD';
export const SELECT_ACTIVE_BOARD_SUCCESS = 'SELECT_ACTIVE_BOARD_SUCCESS';

export const ENABLE_LIST_EDIT_MODE = 'ENABLE_LIST_EDIT_MODE';
export const DISABLE_LIST_EDIT_MODE = 'DISABLE_LIST_EDIT_MODE';

export const SUBMIT_LIST = 'SUBMIT_LIST';
export const SUBMIT_ITEM = 'SUBMIT_ITEM';

export const DELETE_BOARD = 'DELETE_BOARD';
export const DELETE_LIST = 'DELETE_LIST';
