export const CREATING_BOARD = 'CREATING_BOARD';
export const CANCEL_CREATING_BOARD = 'CANCEL_CREATING_BOARD';
export const SUBMIT_BOARD = 'SUBMIT_BOARD';
export const PUT_BOARD_INTO_COLLECTION = 'PUT_BOARD_INTO_COLLECTION';